### ISSUE TITLE
Throws on missing check() for Meteor > 1.2.x when using Tinytest

### ISSUE THREAD

**Issue by ErikAbele** [kadirahq/meteor-debug#19]
See above; you probably just missed an api.use('check') in your package.js...

```
I20150930-16:44:06.355(2)? Exception while invoking method 'kadira.debug.getBrowserName' { stack: 'ReferenceError: check is not defined
at [object Object].Meteor.methods.kadira.debug.getBrowserName (packages/kadira_debug/packages/kadira_debug.js:265:1)
at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2554:1)
at packages/check/match.js:109:1
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
at maybeAuditArgumentChecks (livedata_server.js:1689:18)
at livedata_server.js:708:19
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at livedata_server.js:706:40
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)',
I20150930-16:44:06.355(2)?   source: 'method' }

I20150930-16:44:06.361(2)? Exception from sub kadira.debug.init id xbCqXCFvnYiKh9DjM { stack: 'ReferenceError: check is not defined
at [object Object]._handler (packages/kadira_debug/packages/kadira_debug.js:219:1)
at packages/check/match.js:109:1
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
at maybeAuditArgumentChecks (livedata_server.js:1689:18)
at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
at [object Object].subscriptionProto._runHandler (packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2604:1)
at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
at packages/meteorhacks_kadira/packages/meteorhacks_kadira.js:2467:1',
I20150930-16:44:06.361(2)?   source: 'subscription' }
```

**Comment by arunoda** [comment]
Yep. It seems like the issue.

**Comment by arunoda** [comment]
Just published a new version with the fix. 
Thanks.

**Comment by ErikAbele** [comment]
Aye, works now – thanks Arunoda!

**Comment by arunoda** [comment]
Awesome.

**Comment by nirarazi** [comment]
This happens to me with Meteor 1.2.1 and today's package. Any solution?

**Comment by arunoda** [comment]
@nirarazi Check whether you are using the latest version. Sometimes, meteor installs a older version.
