### ISSUE TITLE
TypeError: Cannot read property 'createDataHandler' of undefined

### ISSUE THREAD

**Issue by rudza** [kadirahq/meteor-debug#42]
When I try to add package `kadira:debug` I get this error:
```
/home/rudolfs/.meteor/packages/meteor-tool/.1.4.1_3.8dq62w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
             				throw(ex);
             				^
           
 TypeError: Cannot read property 'createDataHandler' of undefined
     at setLabels (packages/meteorhacks_kadira/lib/hijack/set_labels.js:10:1)
     at packages/meteorhacks_kadira/lib/hijack/session.js:32:1
     at runWithAFiber (packages/meteorhacks_meteorx/lib/server.js:33:1)
     at packages/meteorhacks_meteorx/lib/server.js:26:1
     at Array.forEach (native)
     at packages/meteorhacks_meteorx/lib/server.js:25:1
     at /home/rudolfs/workspace/syp/.meteor/local/build/programs/server/boot.js:299:5
=> Exited with code: 1                        
=> Your application is crashing. Waiting for file change.
```
Meteor version: 1.4.1.3

https://kadira.io/platform/kadira-debug/overview - This says to use `kadira:debug`
But here: https://kadira.io/academy/meteor-performance-101/content/understanding-your-meteor-app - it says to use `meteorhacks:kadira-debug`

`kadira:debug` throws an error, but `meteorhacks:kadira-debug` is not recognized by http://debug.kadiraio.com/debug

**Comment by rudza** [comment]
Fixed by adding:

`meteorhacks:kadira` and then `kadira:debug`
